version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./_nginx/vhost/:/etc/nginx/vhost.d:rw
      - ./_nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:rw
      - ./_nginx/html:/usr/share/nginx/html
      - ./app/static:/code/static
      - ./app/media:/code/media
  
  redis:
    container_name: redis
    image: redis:5
    restart: "always"
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/var/lib/redis

  postgres:
    container_name:  postgres
    image:           postgres
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  app:
    container_name: app
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=165.22.83.150
      - VIRTUAL_PORT=8015
      - HTTP_PORT=8015
      - DEBUG=True
      - STATS_PORT=8001
      - LANG=C.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./app:/code
      - ./uwsgi.ini:/conf/uwsgi.ini
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8015:8015"

  celery:
    container_name: celery
    build: .
    restart: "always"
    command: celery --app=app.celery:app worker -B --loglevel=DEBUG
    env_file: .env
    volumes:
      - ./app:/code:rw
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

networks:
  default:
    external:
      name: nginx-proxy